<?php
// This script scans the slideshow directory and generates a JavaScript file with the list of images

// Directory to scan
$directory = 'images/slideshow/';

// Get all image files from the directory
$images = [];
$allowed_extensions = ['jpg', 'jpeg', 'png', 'gif', 'webp', 'JPG', 'JPEG', 'PNG', 'GIF', 'WEBP'];

if (is_dir($directory)) {
    if ($handle = opendir($directory)) {
        while (($file = readdir($handle)) !== false) {
            // Skip . and .. directories
            if ($file == '.' || $file == '..') {
                continue;
            }
            
            // Check if the file has an allowed extension
            $extension = pathinfo($file, PATHINFO_EXTENSION);
            if (in_array($extension, $allowed_extensions)) {
                $images[] = $directory . $file;
            }
        }
        closedir($handle);
    }
}

// Generate JavaScript file content
$js_content = "// This file is automatically generated by generate-slideshow-list.php\n";
$js_content .= "// Do not edit this file directly\n\n";
$js_content .= "const slideshowImages = [\n";

foreach ($images as $image) {
    $js_content .= "    '" . $image . "',\n";
}

$js_content .= "];\n";

// Write to JavaScript file
file_put_contents('slideshow-images.js', $js_content);

echo "Slideshow image list generated successfully!\n";
echo "Found " . count($images) . " images in the slideshow directory.\n";
?>