// This file is automatically generated by generate-slideshow-list.php
// Do not edit this file directly

const slideshowImages = [
    'images/slideshow/bg.jpg',
    'images/slideshow/walpaper.jpg',
];