// This file is automatically generated by generate-slideshow-list.php
// Do not edit this file directly

const slideshowImages = [
    'images/slideshow/pic01.jpg',
    'images/slideshow/testPic.jpg',
    'images/slideshow/Far_de_Cavaleria.JPG',
];
